// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHK5pxBgRrUl812B6TOxRi1gMn5BOD5vk',
    appId: '1:301231659993:web:ec9d20ebd417d2b6cd97c8',
    messagingSenderId: '301231659993',
    projectId: 'project-mu-safe-campus',
    authDomain: 'project-mu-safe-campus.firebaseapp.com',
    storageBucket: 'project-mu-safe-campus.firebasestorage.app',
    measurementId: 'G-9J0JSJQ0N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbTiJ4QrxVhONU2yREYsKmONZnGpAvKPU',
    appId: '1:301231659993:android:59d5ae3551dcea26cd97c8',
    messagingSenderId: '301231659993',
    projectId: 'project-mu-safe-campus',
    storageBucket: 'project-mu-safe-campus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9GXW_Z0vzgZGPhkEIzG8n6fUoJAhuSeY',
    appId: '1:301231659993:ios:9c7db8022714c93ecd97c8',
    messagingSenderId: '301231659993',
    projectId: 'project-mu-safe-campus',
    storageBucket: 'project-mu-safe-campus.firebasestorage.app',
    iosBundleId: 'com.example.projectMuCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9GXW_Z0vzgZGPhkEIzG8n6fUoJAhuSeY',
    appId: '1:301231659993:ios:9c7db8022714c93ecd97c8',
    messagingSenderId: '301231659993',
    projectId: 'project-mu-safe-campus',
    storageBucket: 'project-mu-safe-campus.firebasestorage.app',
    iosBundleId: 'com.example.projectMuCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHK5pxBgRrUl812B6TOxRi1gMn5BOD5vk',
    appId: '1:301231659993:web:3a2d5291bd4165ffcd97c8',
    messagingSenderId: '301231659993',
    projectId: 'project-mu-safe-campus',
    authDomain: 'project-mu-safe-campus.firebaseapp.com',
    storageBucket: 'project-mu-safe-campus.firebasestorage.app',
    measurementId: 'G-VRDLMH3YE5',
  );
}
